// VEHICLE ACTION TYPES
export const GET_ALL_VEHICLES_REQUEST = 'GET_ALL_VEHICLES_REQUEST';
export const GET_ALL_VEHICLES_SUCCESS = 'GET_ALL_VEHICLES_SUCCESS';
export const GET_ALL_VEHICLES_FAIL = 'GET_ALL_VEHICLES_FAIL';

export const GET_VEHICLE_BY_ID_REQUEST = 'GET_VEHICLE_BY_ID_REQUEST';
export const GET_VEHICLE_BY_ID_SUCCESS = 'GET_VEHICLE_BY_ID_SUCCESS';
export const GET_VEHICLE_BY_ID_FAIL = 'GET_VEHICLE_BY_ID_FAIL';

export const GET_VEHICLE_DOORS_REQUEST = 'GET_VEHICLE_DOORS_REQUEST';
export const GET_VEHICLE_DOORS_SUCCESS = 'GET_VEHICLE_DOORS_SUCCESS';
export const GET_VEHICLE_DOORS_FAIL = 'GET_VEHICLE_DOORS_FAIL';

export const SET_DOORS_LOCK_REQUEST = 'SET_DOORS_LOCK_REQUEST';
export const SET_DOORS_LOCK_SUCCESS = 'SET_DOORS_LOCK_SUCCESS';
export const SET_DOORS_LOCK_FAIL = 'SET_DOORS_LOCK_FAIL';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';



